"""empty message

Revision ID: 51476fab1ebe
Revises: 51b77f9526e1
Create Date: 2021-11-02 12:37:07.825874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51476fab1ebe'
down_revision = '51b77f9526e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('age', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actors', 'age')
    # ### end Alembic commands ###
