"""empty message

Revision ID: 51b77f9526e1
Revises: 
Create Date: 2021-11-02 12:34:58.174551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b77f9526e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actors', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('age', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
